x = 1:50;
x = 2000 + 100*x;
x = log10(x);
T_C = (3/4)*T_R;
extraInputs = {'interpreter','latex','fontsize',19};
plot(x,T_R,'-k',x,T_G,'-b',x,T_N,'-r',x,T_C,'-g');
xlabel('Logarithmic Dimension of the Matrices',extraInputs{:});
ylabel('Computation Time',extraInputs{:});
legend({'Regular', 'Gauss', 'New','3/4 of Regular'},extraInputs{:});
legend('Location','northwest');
%saveas(gcf, 'speed_plot_new.png');